#lang racket/base

(provide (all-defined-out))

(define (make-env builtins)
  (let ((vars (map car builtins))
        (vals (map cdr builtins)))
    (cons (make-hash)
          (subst vars vals '()))))

(define (subst vars vals env)
  (if (= (length vars) (length vals))
      (let ((env* (cons (make-hash) env)))
        (for ((var (in-list vars))
              (val (in-list vals)))
          (define-var var val env*))
        env*)
      (error "arity mismatch:" vars vals)))

(define (define-var var val env)
  (let ((frame (car env)))
    (if (hash-has-key? frame var)
        (error "already defined:" var)
        (hash-set! frame var val))))

(define (get-var var env)
  (if (null? env)
      (error "undefined:" var)
      (let ((frame (car env)))
        (if (hash-has-key? frame var)
            (hash-ref frame var)
            (get-var var (cdr env))))))

(define (set-var var val env)
  (if (null? env)
      (error "undefined:" var)
      (let ((frame (car env)))
        (if (hash-has-key? frame var)
            (hash-set! frame var val)
            (set-var var val (cdr env))))))
