#lang sicp

(define (foldr proc init l)
  (letrec ((f (lambda (l)
                (if (null? l)
                    init
                    (proc (car l)
                          (f (cdr l)))))))
    (f l)))

(define (flatmap proc l)
  (foldr append '() (map proc l)))

(define (enumerate-interval low high)
  (letrec ((e (lambda (i result)
                (if (< i low)
                    result
                    (e (dec i) (cons i result))))))
    (e high '())))

(define (filter pred? l)
  (letrec ((f (lambda (l result)
                (cond ((null? l)
                       result)
                      ((pred? (car l))
                       (f (cdr l)
                          (cons (car l) result)))
                      (else
                       (f (cdr l)
                          result))))))
    (f l '())))

(define (triples-sum-to-s s n)
  (let ((triples (flatmap (lambda (i)
                            (flatmap (lambda (j)
                                       (map (lambda (k)
                                              (list i j k))
                                            (enumerate-interval 1 n)))
                                     (enumerate-interval 1 n)))
                          (enumerate-interval 1 n)))
        (sum-to-s? (lambda (t)
                     (= (+ (car t)
                           (cadr t)
                           (caddr t))
                        s))))
    (filter sum-to-s? triples)))

(define (displayln x)
  (display x)
  (newline))

(for-each displayln (triples-sum-to-s 6 6))
;; (4 1 1)
;; (3 2 1)
;; (3 1 2)
;; (2 3 1)
;; (2 2 2)
;; (2 1 3)
;; (1 4 1)
;; (1 3 2)
;; (1 2 3)
;; (1 1 4)
