#lang sicp

(define (make-queue)
  (let* ((front-ptr '())
         (rear-ptr '())
         (insert! (lambda (item)
                    (let ((node (cons item '())))
                      (if (null? front-ptr)
                          (set! front-ptr node)
                          (set-cdr! rear-ptr node))
                      (set! rear-ptr node))))
         (delete! (lambda ()
                    (if (null? front-ptr)
                        (error "make-queue: delete!: empty queue")
                        (set! front-ptr (cdr front-ptr)))))
         (print (lambda ()
                  (display front-ptr)
                  (newline)))
         (dispatch (lambda (m)
                     (case m
                       ('insert! insert!)
                       ('delete! delete!)
                       ('print print)
                       (else (error "queue: unknown method:" m))))))
    dispatch))

(define (insert-queue! q item)
  ((q 'insert!) item)
  q)

(define (delete-queue! q)
  ((q 'delete!))
  q)

(define (print-queue q)
  ((q 'print)))

(let ((q (make-queue)))
  (insert-queue! q 'a)
  (print-queue q)
  (insert-queue! q 'b)
  (print-queue q)
  (delete-queue! q)
  (print-queue q)
  (delete-queue! q)
  (print-queue q))
;; (a)
;; (a b)
;; (b)
;; ()
