#lang sicp

(define (make-new-machine)
  (letrec ((pc (make-register 'pc))
           (flag (make-register 'flag))
           (stack (make-stack))
           (the-instruction-sequence '())
           (the-ops (list (list 'initialize-stack
                                (lambda ()
                                  (stack 'initialize)))))
           (register-table (list (list 'pc pc)
                                 (list 'flag flag)))
           (allocate-register (lambda (name)
                                (if (assoc name register-table)
                                    (error "multiply defined register:" name)
                                    (set! register-table
                                          (cons (list name (make-register name))
                                                register-table)))
                                'register-allocated))
           (lookup-register (lambda (name)
                              (let ((val (assoc name register-table)))
                                (if val
                                    (cadr val)
                                    (error "unknown register:" name)))))
           (execute (lambda ()
                      (let ((insts (get-contents pc)))
                        (if (null? insts)
                            'done
                            (begin ((instruction-execution-proc (car insts)))
                                   (execute))))))
           (dispatch (lambda (message)
                       (cond ((eq? message 'start)
                              (set-contents! pc the-instruction-sequence)
                              (execute))
                             ((eq? message 'install-instruction-sequence)
                              (lambda (seq)
                                (set! the-instruction-sequence seq)))
                             ((eq? message 'allocate-register)
                              allocate-register)
                             ((eq? message 'get-register)
                              lookup-register)
                             ((eq? message 'install-operations)
                              (lambda (ops)
                                (set! the-ops (append the-ops ops))))
                             ((eq? message 'stack)
                              stack)
                             ((eq? message 'operations)
                              the-ops)
                             (else (error "machine: unknown request:" message))))))
    dispatch))
